DROP FUNCTION service_calendar.save_operating_periods;

DROP VIEW service_calendar.substitute_operating_period_with_date_range;

ALTER TABLE
    ONLY service_calendar.substitute_operating_day_by_line_type DROP COLUMN substitute_operating_period_id;

DROP TABLE service_calendar.substitute_operating_period;