---
version: "3.8"
services:
  postgis:
    image: "hsldevcom/jore4-postgres:azuredbmock"
    restart: "unless-stopped"
    networks:
      - jore4
    env_file: "./.env"
    environment:
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
    secrets:
      - source: db-auth-username
        target: /mnt/secrets-store/db-auth-username
      - source: db-auth-password
        target: /mnt/secrets-store/db-auth-password
      - source: db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username
      - source: db-jore3importer-password
        target: /mnt/secrets-store/db-jore3importer-password

  hasura:
    build: .
    restart: "unless-stopped"
    networks:
      - jore4
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    secrets:
      - db-username
      - db-password
      - db-hostname
      - db-name
      - hasura-admin-secret
      - db-auth-username
      - db-jore3importer-username

networks:
  jore4:

secrets:
  db-username:
    file: ./secrets/db-username
  db-password:
    file: ./secrets/db-password
  db-hostname:
    file: ./secrets/db-hostname
  db-name:
    file: ./secrets/db-name
  hasura-admin-secret:
    file: ./secrets/hasura-admin-secret
  db-auth-username:
    file: ./secrets/db-auth-username
  db-auth-password:
    file: ./secrets/db-auth-password
  db-jore3importer-username:
    file: ./secrets/db-jore3importer-username
  db-jore3importer-password:
    file: ./secrets/db-jore3importer-password
