---
version: "3.8"
services:
  postgis:
    # Try to match postgis used in Azure to avoid compatability issues. See which version azure currently supports from documentation: https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions
    image: "postgis/postgis:12-3.0-alpine"
    restart: "unless-stopped"
    networks:
      jore:
        aliases:
          - postgis
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 30s
      start_period: 5s
      timeout: 10s
      retries: 3

  hasura:
    build: .
    restart: "unless-stopped"
    networks:
      jore:
        aliases:
          - hasura
    depends_on:
      postgis:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET:-hasura-admin-secret-key}"
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgis:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      start_period: 5s
      timeout: 10s
      retries: 3

networks:
  jore:
    name: jore4
