DROP TRIGGER check_infrastructure_link_route_link_direction_trigger
  ON infrastructure_network.infrastructure_link;

DROP FUNCTION infrastructure_network.check_infrastructure_link_route_link_direction();


DROP TRIGGER check_route_link_infrastructure_link_direction_trigger
  ON route.infrastructure_link_along_route;

DROP FUNCTION route.check_route_link_infrastructure_link_direction();
