
DROP TRIGGER verify_route_start_end_stop_points_by_old_and_new_link_id_trigger
  ON internal_service_pattern.scheduled_stop_point;

DROP TRIGGER verify_route_start_end_stop_points_by_old_and_new_route_id_trigger
  ON route.infrastructure_link_along_route;

DROP TRIGGER verify_route_start_end_stop_points_by_new_route_id_trigger
  ON internal_route.route;

DROP FUNCTION route.verify_route_start_end_stop_points_by_old_and_new_link_id();

DROP FUNCTION route.verify_route_start_end_stop_points_by_old_and_new_route_id();

DROP FUNCTION route.verify_route_start_end_stop_points_by_new_route_id();

DROP FUNCTION route.verify_route_start_end_stop_points(param_route_id UUID);
