DROP SCHEMA IF EXISTS infrastructure_network CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;
DROP EXTENSION IF EXISTS postgis CASCADE;
DROP SCHEMA IF EXISTS pgcrypto CASCADE;
DROP SCHEMA IF EXISTS postgis CASCADE;
ALTER DATABASE ' || current_database() || ' RESET search_path;
