DROP TRIGGER prevent_insertion_to_distance_between_stops_calculation ON service_pattern.distance_between_stops_calculation;
DROP FUNCTION service_pattern.prevent_inserting_distance_between_stops_calculation;
