---
version: '3.8'

services:
  jore4-hasura:
    # build and the docker image from the local repo
    build:
      context: ..
      target: hasura-generic
    environment:
      # enabling the hasura console locally to ease development
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
