ALTER TABLE service_calendar.substitute_operating_day DROP CONSTRAINT substitute_operating_day_type_exclusion;
ALTER TABLE service_calendar.substitute_operating_day DROP CONSTRAINT substitute_operating_day_no_timespan_overlap;
ALTER TABLE service_calendar.substitute_operating_day DROP CONSTRAINT substitute_operating_day_valid_end_time;
ALTER TABLE service_calendar.substitute_operating_day DROP CONSTRAINT substitute_operating_day_valid_begin_time;
ALTER TABLE service_calendar.substitute_operating_day DROP CONSTRAINT substitute_operating_day_reference_date_nullability;
