DROP TRIGGER check_infrastructure_link_scheduled_stop_points_direction_trigger
  ON infrastructure_network.infrastructure_link;

DROP FUNCTION infrastructure_network.check_infrastructure_link_scheduled_stop_points_direction_trigger();


DROP TRIGGER check_scheduled_stop_point_infrastructure_link_direction_trigger
  ON internal_service_pattern.scheduled_stop_point;

DROP FUNCTION internal_service_pattern.check_scheduled_stop_point_infrastructure_link_direction();
