
DROP TRIGGER verify_infra_link_order_on_journey_pattern_trigger ON journey_pattern.journey_pattern;

DROP TRIGGER verify_infra_link_order_on_scheduled_stop_point_trigger ON internal_service_pattern.scheduled_stop_point;

DROP TRIGGER verify_infra_link_order_on_infrastructure_link_along_route_trigger ON route.infrastructure_link_along_route;

DROP TRIGGER verify_infra_link_order_on_scheduled_stop_point_in_journey_pattern_trigger ON journey_pattern.scheduled_stop_point_in_journey_pattern;


DROP FUNCTION journey_pattern.verify_infra_link_order_by_new_scheduled_stop_point_id();

DROP FUNCTION journey_pattern.verify_infra_link_order_by_old_route_id();

DROP FUNCTION journey_pattern.verify_infra_link_order_by_new_journey_pattern_id();


DROP FUNCTION journey_pattern.verify_journey_pattern_infra_link_order(
  filter_journey_pattern_id uuid,
  filter_route_id uuid
);

DROP FUNCTION journey_pattern.infra_link_order_map_by_route_id(
  filter_route_id uuid
);

DROP FUNCTION journey_pattern.infra_link_order_map_by_journey_pattern_id(
  filter_journey_pattern_id uuid
);
