name: Check if sources have been prettified

on:
  # this workflow is only called by others, won't be executed on itself
  workflow_call:
  workflow_dispatch:

jobs:
  check_prettify:
    name: Check if sources have been prettified
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prettify sources
        run: ./scripts/prettify.sh

      - name: Verify that prettify command made no changes
        run: '[ -z "$(git status --porcelain)" ]'
